using System;
using System.Collections.Generic;
using UnityEngine;

namespace RoguelikeMap
{
    /// <summary>
    /// Layer data used in MapConfig files.
    /// </summary>
    [Serializable]
    public class MapLayer
    {
        /// <summary>
        /// whether the nodes in this layer is pre-defined or should be generated by Procedual generation algorithm
        /// </summary>
        [Tooltip("whether the nodes in this layer is pre-defined or should be generated by Procedual generation algorithm")]
        public bool randomizedLayer;
        /// <summary>
        /// The node list used If the layer is a pre-defined layer;
        /// </summary>
        [Tooltip("The node list used If the layer is a pre-defined layer.")]
        public List<PredefinedNodeData> layerNodes;
        /// <summary>
        /// Potential Node types with weight in this layer.
        /// Used to generate random Nodes;
        /// </summary>
        [Tooltip("Potential Node types with weight in this layer.Used to generate random Nodes.")]
        public List<NodeTypeWeightData> weightedPotentialNodeTypes;
        /// <summary>
        /// The range for number of nodes in this layer;
        /// </summary>
        public int minNodeSize;
        public int maxNodeSize;
    }

}
